name: 'Continuous Integration'

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10.2']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10.2
        uses: actions/setup-python@v5.2.0
        with:
          python-version: 3.10.2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt  # Install other dependencies

      - name: Run api-test
        run: |
          make api-test 
