name: 'Continuous Integration'

on:
  push:
    branches:
      - 'feature/*'
      - 'hotfix/*'
      - 'release/*'
      - 'develop'
      - 'main'
  pull_request:
    branches:
      - 'develop'
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/auth@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Build the Docker image
      run: |
        gcloud builds submit --quiet --suppress-logs --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-cloud-run-app-test \
        --gcs-log-dir=gs://ds-francis-logs/

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy my-cloud-run-app-test --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-cloud-run-app-test --platform managed --region us-central1 --allow-unauthenticated

    - name: Delete Cloud Run service
      run: |
        gcloud run services delete my-cloud-run-app-test --quiet